### PR TITLE
/etc/sudoers should be 0440, not 0660 in Docker images

### PR DESCRIPTION
**Pull request by rouge8**
Attempting to build buzzy with the Ubuntu 12.04 Docker image fails with the error:

    sudo: /etc/sudoers is mode 0660, should be 0440
    sudo: no valid sudoers sources found, quitting
    sudo: unable to initialize policy plugin

### CODE REVIEW

**Comment by dcreager** [comment]
This looks great!  As of #31, though, I'm building the docker images from a [different repo](/redjack/buzzy-docker).  That other repo is what's being used to generate the `buzzy/*` and `buzzy/build-*` images in the public Docker registry, even though I lazily haven't merged in #31 yet.

**Comment by rouge8** [comment]
I saw #31, but I wasn't sure if there was a reason it's not merged yet.

**Comment by dcreager** [comment]
Not a good one.  I have to remember to unset `MAKEFLAGS`.  I'm going to merge it.

**Comment by dcreager** [comment]
It's done!  Live life on the edge

**Pull request closed without merging**
